[package]
name = "hustoa-vm"
version = "0.1.2"
edition = "2021"
authors = ["Yalong Zou <yalongz@hust.edu.cn>"]

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
colored = "2.1.0"
enum_dispatch = "0.3.13"
env_logger = "0.11.3"
hex = "0.4.3"
lazy_static = "1.5.0"
log = "0.4.21"
rand = "0.8.5"
semver = "1.0.23"
serde = { version = "1.0.203", features = ["derive"] }
serde_yml = "0.0.12"
slugify = "0.1.0"
tempfile = "3.12.0"
toml = "0.8.13"
which = "6.0.3"
