[[distro]]
name = "ubuntu"
latest_version = "noble"

[[distro.versions]]
name = "noble"
alias = ["24.04", "24"]
osinfo_conf = "ubuntu-stable-latest"

[[distro.versions]]
name = "jammy"
alias = ["22.04", "22"]
osinfo_conf = "ubuntujammy"

[[distro.versions]]
name = "focal"
alias = ["20.04", "20"]
osinfo_conf = "ubuntufocal"

[[distro.versions]]
name = "bionic"
alias = ["18.04", "18"]
osinfo_conf = "ubuntubionic"

[[distro]]
name = "debian"
latest_version = "bookworm"

[[distro.versions]]
name = "bookworm"
alias = ["12"]
# debian12 is not listed in virt-install --osinfo
osinfo_conf = "debian11"

[[distro.versions]]
name = "bullseye"
alias = ["11"]
osinfo_conf = "debian11"

[[distro.versions]]
name = "buster"
alias = ["10"]
osinfo_conf = "debian10"

[[distro]]
name = "archlinux"
latest_version = "rolling"

[[distro.versions]]
name = "rolling"
alias = []
osinfo_conf = "archlinux"
